let marks = [91, 34, 56, 67, 65, 35, 89, false, "not present"];
console.log(marks);
console.log(marks[0]);
console.log(marks[1]);
console.log(marks[2]);
console.log(marks[3]);
console.log(marks[4]);
console.log(marks[5]);
console.log(marks[6]);
console.log(marks[7]);
console.log(marks[8]);
console.log(marks[9]);
console.log("The length of marks is", marks.length);
marks[9] = 98;
marks[0] = 99;
console.log(marks);
console.log(typeof marks);
